FROM apache/superset:latest
# Chuyển sang quyền root để cài đặt thư viện
USER root
# Cài đặt psycopg2-binary thẳng vào thư mục ảo của superset để kết nối PostgreSQL
RUN pip install psycopg2-binary --target=/app/.venv/lib/python3.10/site-packages/ --force-reinstall --no-deps
# Quay lại user mặc định của hệ thống
USER superset
